mybatis:
  mapperLocations: classpath*:**/mapping/*.xml   #mapper文件的位置
  #typeAliasesPackage: classpath:**.model   #为实体对象所在的包，跟数据库表一一对应
spring:
  datasource:
      name: darkhole
      #url: jdbc:mysql://192.168.31.10:3306/dangan?useUnicode=true&characterEncoding=utf8
      url: jdbc:mysql://127.0.0.1:3306/darkhole?useUnicode=true&characterEncoding=utf8
      #url: jdbc:mysql://211.149.149.227:3306/dangan?useUnicode=true&characterEncoding=utf8
      #url: jdbc:mysql://192.168.31.10:3306/dangan?useUnicode=true&characterEncoding=utf8
      username: root
      password: root
      #username: root
      #password: root
      type: com.alibaba.druid.pool.DruidDataSource  #使用druid数据源
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
logging:
  level:
    com.onepro.custom.mapper: DEBUG